apiVersion: v1
kind: Service
metadata:
  name: traceback-frontend-service

spec:
  selector:
    app: traceback-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

  type: NodePort