apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceback-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: traceback-frontend

  template:
    metadata:
      labels:
        app: traceback-frontend

    spec:
      containers:
        - name: frontend
          image: traceback-frontend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80