apiVersion: v1
kind: Service
metadata:
  name: traceback-mongo-service

spec:
  selector:
    app: traceback-mongo

  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

  type: ClusterIP